apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath
  namespace: openebs
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/openebs/local
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - c6100-s01-eth0
    - c6100-s02-eth0
    - c6100-s03-eth0
    - c6100-s04-eth0
    - r610-5bf035j-eth0